version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.11.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
  
  logstash:
    image: logstash:7.11.1
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.11.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
