/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CalcCoreJNI */

#ifndef _Included_CalcCoreJNI
#define _Included_CalcCoreJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CalcCoreJNILib_CalcCoreJNI
 * Method:    getExpressionResult
 * Signature: (Ljava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_calc_CalcCoreJNILib_CalcCoreJNI_getExpressionResult(JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     CalcCoreJNILib_CalcCoreJNI
 * Method:    getGraphResult
 * Signature: (Ljava/lang/String;LCalcCoreJNILib/dto/GraphData;)LCalcCoreJNILib/dto/GraphResult;
 */
JNIEXPORT jobject JNICALL Java_calc_CalcCoreJNILib_CalcCoreJNI_getGraphResult(JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
